import time
print("Starting Hack....")
time.sleep(5)
print("Hacking FBI 10%")
time.sleep(5)
print("Hacking FBI 20%")
time.sleep(5)
print("Hacking FBI 30%")
time.sleep(5)
print("Hacking FBI 40%")
time.sleep(5)
print("Hacking FBI 50%")
time.sleep(5)
print("Timeout")
time.sleep(1)
print("Timeout")
time.sleep(1)
print("Timeout")
time.sleep(1)
print("Timeout")
time.sleep(1)
print("Hacking FBI 60%")
time.sleep(5)
print("Hacking FBI 70%")
time.sleep(5)
print("Hacking FBI 80%")
time.sleep(5)
print("Hacking FBI 90%")
time.sleep(5)
print("Hacking FBI 100%")
time.sleep(5)
print("FBI Hacked successfully")